# Generated by Django 4.1 on 2022-08-16 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('source_code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('planned_finish_by_date', models.DateTimeField()),
                ('actual_finish_by_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=30)),
                ('wage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_by_date', models.DateTimeField()),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.module')),
                ('admin_programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.programmer')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.programmer'),
        ),
    ]
